language: node_js
node_js:
  - 10.16
install:
  - npm install
jobs:
  include:
    - stage: test
      script: 
        - npm run demo-app:lint
        - npm run ngxs-effect:lint
        - npm run ngxs-effect:test
        - npm run ngxs-effect:build
    - stage: master
      if: branch = master
      script:
        - npm run ngxs-effect:test
        - npm run ngxs-effect:build
        - npm run coveralls

  
